[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.5",
    "confluent-kafka>=2.15.0",
    "docker>=7.2.0",
    "fastapi>=0.139.2",
    "psycopg2-binary>=2.9.12",
    "pydantic-settings>=2.14.2",
    "python-dotenv>=1.2.2",
    "redis>=8.0.1",
    "sqlalchemy>=2.0.51",
    "upstash-redis>=1.7.0",
    "uvicorn>=0.51.0",
    "websockets>=16.1.1",
]
